package dev.cubecrafttd.testing

import dev.cubecrafttd.arena.TeamId
import dev.cubecrafttd.map.*
import dev.cubecrafttd.map.importer.*

/**
 * Generated from CubeCraft_TD_Farm_runtime_candidate_v2.json.
 * Authenticity remains COMMUNITY_IMPROVEMENT_BY_ORIGINAL_TRACK_AUTHOR.
 * This is not a production-original Farm claim.
 */
object FarmFullRuntimeFixture {
    const val EXPECTED_SHA256 = "28d24136afe80358b89556d0fbe3b08d00e518af38c7c518819fa7fc225e613e"

    private val blueHigh = listOf(
            Vec3(98.0, 8.0, 116.0),
            Vec3(98.0, 8.0, 99.0),
            Vec3(106.0, 8.0, 99.0),
            Vec3(106.0, 8.0, 92.0),
            Vec3(108.0, 8.0, 92.0),
            Vec3(108.0, 8.0, 68.0),
            Vec3(106.0, 8.0, 68.0),
            Vec3(106.0, 8.0, 61.0),
            Vec3(98.0, 8.0, 61.0),
            Vec3(98.0, 8.0, 40.0),
            Vec3(110.0, 8.0, 40.0),
            Vec3(110.0, 8.0, 16.0),
            Vec3(86.0, 8.0, 16.0),
            Vec3(86.0, 8.0, 28.0),
            Vec3(56.0, 8.0, 28.0),
            Vec3(56.0, 8.0, 13.0),
            Vec3(52.0, 8.0, 13.0),
            Vec3(51.0, 7.0, 13.0),
            Vec3(50.0, 7.0, 13.0),
            Vec3(49.0, 6.0, 13.0),
            Vec3(48.0, 6.0, 13.0),
            Vec3(47.0, 5.0, 13.0),
            Vec3(46.0, 5.0, 13.0),
            Vec3(45.0, 4.0, 13.0),
            Vec3(44.0, 4.0, 13.0),
            Vec3(43.0, 3.0, 13.0),
            Vec3(38.0, 3.0, 13.0),
            Vec3(38.0, 3.0, 45.0),
            Vec3(62.0, 3.0, 45.0),
            Vec3(62.0, 3.0, 65.0)
    )
    private val blueLow = listOf(
            Vec3(98.0, 8.0, 116.0),
            Vec3(98.0, 8.0, 99.0),
            Vec3(90.0, 8.0, 99.0),
            Vec3(90.0, 8.0, 92.0),
            Vec3(88.0, 8.0, 92.0),
            Vec3(88.0, 8.0, 68.0),
            Vec3(90.0, 8.0, 68.0),
            Vec3(90.0, 8.0, 61.0),
            Vec3(98.0, 8.0, 61.0),
            Vec3(98.0, 8.0, 40.0),
            Vec3(110.0, 8.0, 40.0),
            Vec3(110.0, 8.0, 16.0),
            Vec3(86.0, 8.0, 16.0),
            Vec3(86.0, 8.0, 28.0),
            Vec3(56.0, 8.0, 28.0),
            Vec3(56.0, 8.0, 13.0),
            Vec3(52.0, 8.0, 13.0),
            Vec3(51.0, 7.0, 13.0),
            Vec3(50.0, 7.0, 13.0),
            Vec3(49.0, 6.0, 13.0),
            Vec3(48.0, 6.0, 13.0),
            Vec3(47.0, 5.0, 13.0),
            Vec3(46.0, 5.0, 13.0),
            Vec3(45.0, 4.0, 13.0),
            Vec3(44.0, 4.0, 13.0),
            Vec3(43.0, 3.0, 13.0),
            Vec3(38.0, 3.0, 13.0),
            Vec3(38.0, 3.0, 45.0),
            Vec3(62.0, 3.0, 45.0),
            Vec3(62.0, 3.0, 65.0)
    )
    private val redHigh = listOf(
            Vec3(26.0, 8.0, 71.0),
            Vec3(26.0, 8.0, 88.0),
            Vec3(18.0, 8.0, 88.0),
            Vec3(18.0, 8.0, 95.0),
            Vec3(16.0, 8.0, 95.0),
            Vec3(16.0, 8.0, 119.0),
            Vec3(18.0, 8.0, 119.0),
            Vec3(18.0, 8.0, 126.0),
            Vec3(26.0, 8.0, 126.0),
            Vec3(26.0, 8.0, 147.0),
            Vec3(14.0, 8.0, 147.0),
            Vec3(14.0, 8.0, 171.0),
            Vec3(38.0, 8.0, 171.0),
            Vec3(38.0, 8.0, 159.0),
            Vec3(68.0, 8.0, 159.0),
            Vec3(68.0, 8.0, 174.0),
            Vec3(72.0, 8.0, 174.0),
            Vec3(73.0, 7.0, 174.0),
            Vec3(74.0, 7.0, 174.0),
            Vec3(75.0, 6.0, 174.0),
            Vec3(76.0, 6.0, 174.0),
            Vec3(77.0, 5.0, 174.0),
            Vec3(78.0, 5.0, 174.0),
            Vec3(79.0, 4.0, 174.0),
            Vec3(80.0, 4.0, 174.0),
            Vec3(81.0, 3.0, 174.0),
            Vec3(86.0, 3.0, 174.0),
            Vec3(86.0, 3.0, 142.0),
            Vec3(62.0, 3.0, 142.0),
            Vec3(62.0, 3.0, 122.0)
    )
    private val redLow = listOf(
            Vec3(26.0, 8.0, 71.0),
            Vec3(26.0, 8.0, 88.0),
            Vec3(34.0, 8.0, 88.0),
            Vec3(34.0, 8.0, 95.0),
            Vec3(36.0, 8.0, 95.0),
            Vec3(36.0, 8.0, 119.0),
            Vec3(34.0, 8.0, 119.0),
            Vec3(34.0, 8.0, 126.0),
            Vec3(26.0, 8.0, 126.0),
            Vec3(26.0, 8.0, 147.0),
            Vec3(14.0, 8.0, 147.0),
            Vec3(14.0, 8.0, 171.0),
            Vec3(38.0, 8.0, 171.0),
            Vec3(38.0, 8.0, 159.0),
            Vec3(68.0, 8.0, 159.0),
            Vec3(68.0, 8.0, 174.0),
            Vec3(72.0, 8.0, 174.0),
            Vec3(73.0, 7.0, 174.0),
            Vec3(74.0, 7.0, 174.0),
            Vec3(75.0, 6.0, 174.0),
            Vec3(76.0, 6.0, 174.0),
            Vec3(77.0, 5.0, 174.0),
            Vec3(78.0, 5.0, 174.0),
            Vec3(79.0, 4.0, 174.0),
            Vec3(80.0, 4.0, 174.0),
            Vec3(81.0, 3.0, 174.0),
            Vec3(86.0, 3.0, 174.0),
            Vec3(86.0, 3.0, 142.0),
            Vec3(62.0, 3.0, 142.0),
            Vec3(62.0, 3.0, 122.0)
    )

    private val explicitSpots = listOf(
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(29, 3, 11), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(32, 3, 11), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(29, 3, 14), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(32, 3, 14), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(32, 3, 17), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(32, 3, 20), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(44, 3, 21), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(32, 3, 23), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(44, 3, 24), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(44, 3, 27), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(44, 3, 30), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(29, 3, 31), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(32, 3, 31), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(44, 3, 33), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(44, 3, 36), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(32, 3, 39), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(44, 3, 39), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(47, 3, 39), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(50, 3, 39), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(53, 3, 39), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(56, 3, 39), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(59, 3, 39), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(62, 3, 39), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(65, 3, 39), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(68, 3, 39), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(71, 3, 39), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(32, 3, 42), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(68, 3, 42), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(71, 3, 42), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(32, 3, 45), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(68, 3, 45), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(71, 3, 45), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(29, 3, 48), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(32, 3, 48), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(29, 3, 51), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(32, 3, 51), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(35, 3, 51), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(38, 3, 51), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(41, 3, 51), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(44, 3, 51), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(47, 3, 51), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(50, 3, 51), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(53, 3, 51), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(56, 3, 51), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(68, 3, 53), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(71, 3, 53), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(56, 3, 54), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(50, 3, 58), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(53, 3, 58), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(56, 3, 58), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(50, 3, 61), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(50, 3, 64), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(110, 8, 7), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(113, 8, 7), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(116, 8, 7), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(119, 8, 7), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(80, 8, 10), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(83, 8, 10), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(86, 8, 10), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(89, 8, 10), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(92, 8, 10), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(95, 8, 10), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(98, 8, 10), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(101, 8, 10), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(104, 8, 10), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(107, 8, 10), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(110, 8, 10), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(113, 8, 10), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(116, 8, 10), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(119, 8, 10), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(80, 8, 13), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(116, 8, 13), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(119, 8, 13), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(62, 8, 16), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(65, 8, 16), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(80, 8, 16), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(116, 8, 16), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(119, 8, 16), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(50, 8, 19), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(62, 8, 19), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(65, 8, 19), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(68, 8, 19), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(71, 8, 19), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(74, 8, 19), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(77, 8, 19), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(80, 8, 19), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(116, 8, 19), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(50, 8, 22), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(62, 8, 22), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(65, 8, 22), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(68, 8, 22), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(71, 8, 22), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(74, 8, 22), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(77, 8, 22), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(80, 8, 22), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(98, 8, 22), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(116, 8, 22), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(50, 8, 25), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(98, 8, 25), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(116, 8, 25), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(50, 8, 28), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(92, 8, 28), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(95, 8, 28), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(98, 8, 28), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(101, 8, 28), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(104, 8, 28), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(116, 8, 28), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(50, 8, 31), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(98, 8, 31), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(116, 8, 31), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(50, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(53, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(56, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(59, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(62, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(65, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(68, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(71, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(74, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(77, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(80, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(83, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(86, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(89, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(98, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(116, 8, 34), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(92, 8, 37), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(116, 8, 37), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(92, 8, 40), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(116, 8, 40), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(92, 8, 43), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(116, 8, 43), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(92, 8, 46), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(104, 8, 46), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(107, 8, 46), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(110, 8, 46), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(113, 8, 46), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(116, 8, 46), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(89, 8, 49), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(92, 8, 49), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(104, 8, 49), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(107, 8, 49), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(89, 8, 52), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(92, 8, 52), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(104, 8, 52), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(107, 8, 52), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(89, 8, 55), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(92, 8, 55), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(104, 8, 55), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(107, 8, 55), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(82, 8, 65), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(114, 8, 65), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(96, 8, 67), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(100, 8, 67), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(82, 8, 68), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(114, 8, 68), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(96, 8, 70), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(100, 8, 70), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(82, 8, 71), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(114, 8, 71), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(94, 8, 74), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(102, 8, 74), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(94, 8, 77), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(102, 8, 77), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(94, 8, 80), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(102, 8, 80), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(94, 8, 83), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(102, 8, 83), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(94, 8, 86), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(102, 8, 86), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(82, 8, 89), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(114, 8, 89), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(96, 8, 90), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(100, 8, 90), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(82, 8, 92), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(114, 8, 92), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(96, 8, 93), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(100, 8, 93), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(82, 8, 95), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(114, 8, 95), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(89, 8, 105), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(92, 8, 105), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(104, 8, 105), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(107, 8, 105), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(89, 8, 108), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(92, 8, 108), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(104, 8, 108), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(107, 8, 108), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(31, 3, 27), FootprintSize.FIVE_BY_FIVE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(69, 3, 49), FootprintSize.FIVE_BY_FIVE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(93, 8, 33), FootprintSize.FIVE_BY_FIVE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(83, 8, 38), FootprintSize.FIVE_BY_FIVE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(83, 8, 61), FootprintSize.FIVE_BY_FIVE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(98, 8, 80), FootprintSize.FIVE_BY_FIVE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(113, 8, 99), FootprintSize.FIVE_BY_FIVE),
            ExplicitTowerSpot(TeamId.BLUE, BlockPos(105, 8, 112), FootprintSize.FIVE_BY_FIVE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(95, 3, 176), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(92, 3, 176), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(95, 3, 173), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(92, 3, 173), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(92, 3, 170), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(92, 3, 167), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(80, 3, 166), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(92, 3, 164), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(80, 3, 163), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(80, 3, 160), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(80, 3, 157), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(95, 3, 156), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(92, 3, 156), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(80, 3, 154), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(80, 3, 151), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(92, 3, 148), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(80, 3, 148), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(77, 3, 148), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(74, 3, 148), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(71, 3, 148), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(68, 3, 148), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(65, 3, 148), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(62, 3, 148), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(59, 3, 148), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(56, 3, 148), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(53, 3, 148), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(92, 3, 145), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(56, 3, 145), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(53, 3, 145), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(92, 3, 142), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(56, 3, 142), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(53, 3, 142), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(95, 3, 139), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(92, 3, 139), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(95, 3, 136), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(92, 3, 136), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(89, 3, 136), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(86, 3, 136), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(83, 3, 136), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(80, 3, 136), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(77, 3, 136), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(74, 3, 136), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(71, 3, 136), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(68, 3, 136), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(56, 3, 134), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(53, 3, 134), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(68, 3, 133), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(74, 3, 129), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(71, 3, 129), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(68, 3, 129), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(74, 3, 126), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(74, 3, 123), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(14, 8, 180), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(11, 8, 180), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(8, 8, 180), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(5, 8, 180), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(44, 8, 177), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(41, 8, 177), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(38, 8, 177), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(35, 8, 177), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(32, 8, 177), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(29, 8, 177), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(26, 8, 177), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(23, 8, 177), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(20, 8, 177), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(17, 8, 177), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(14, 8, 177), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(11, 8, 177), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(8, 8, 177), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(5, 8, 177), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(44, 8, 174), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(8, 8, 174), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(5, 8, 174), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(62, 8, 171), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(59, 8, 171), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(44, 8, 171), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(8, 8, 171), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(5, 8, 171), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(74, 8, 168), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(62, 8, 168), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(59, 8, 168), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(56, 8, 168), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(53, 8, 168), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(50, 8, 168), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(47, 8, 168), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(44, 8, 168), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(8, 8, 168), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(74, 8, 165), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(62, 8, 165), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(59, 8, 165), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(56, 8, 165), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(53, 8, 165), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(50, 8, 165), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(47, 8, 165), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(44, 8, 165), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(26, 8, 165), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(8, 8, 165), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(74, 8, 162), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(26, 8, 162), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(8, 8, 162), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(74, 8, 159), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(32, 8, 159), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(29, 8, 159), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(26, 8, 159), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(23, 8, 159), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(20, 8, 159), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(8, 8, 159), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(74, 8, 156), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(26, 8, 156), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(8, 8, 156), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(74, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(71, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(68, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(65, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(62, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(59, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(56, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(53, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(50, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(47, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(44, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(41, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(38, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(35, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(26, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(8, 8, 153), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(32, 8, 150), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(8, 8, 150), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(32, 8, 147), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(8, 8, 147), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(32, 8, 144), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(8, 8, 144), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(32, 8, 141), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(20, 8, 141), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(17, 8, 141), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(14, 8, 141), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(11, 8, 141), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(8, 8, 141), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(35, 8, 138), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(32, 8, 138), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(20, 8, 138), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(17, 8, 138), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(35, 8, 135), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(32, 8, 135), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(20, 8, 135), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(17, 8, 135), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(35, 8, 132), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(32, 8, 132), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(20, 8, 132), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(17, 8, 132), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(42, 8, 122), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(10, 8, 122), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(28, 8, 120), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(24, 8, 120), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(42, 8, 119), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(10, 8, 119), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(28, 8, 117), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(24, 8, 117), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(42, 8, 116), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(10, 8, 116), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(30, 8, 113), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(22, 8, 113), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(30, 8, 110), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(22, 8, 110), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(30, 8, 107), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(22, 8, 107), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(30, 8, 104), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(22, 8, 104), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(30, 8, 101), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(22, 8, 101), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(42, 8, 98), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(10, 8, 98), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(28, 8, 97), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(24, 8, 97), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(42, 8, 95), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(10, 8, 95), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(28, 8, 94), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(24, 8, 94), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(42, 8, 92), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(10, 8, 92), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(35, 8, 82), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(32, 8, 82), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(20, 8, 82), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(17, 8, 82), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(35, 8, 79), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(32, 8, 79), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(20, 8, 79), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(17, 8, 79), FootprintSize.THREE_BY_THREE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(93, 3, 160), FootprintSize.FIVE_BY_FIVE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(55, 3, 138), FootprintSize.FIVE_BY_FIVE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(31, 8, 154), FootprintSize.FIVE_BY_FIVE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(41, 8, 149), FootprintSize.FIVE_BY_FIVE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(41, 8, 126), FootprintSize.FIVE_BY_FIVE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(26, 8, 107), FootprintSize.FIVE_BY_FIVE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(11, 8, 88), FootprintSize.FIVE_BY_FIVE),
            ExplicitTowerSpot(TeamId.RED, BlockPos(19, 8, 75), FootprintSize.FIVE_BY_FIVE)
    )

    fun candidate(): MapImportCandidate {
        val redTerminalCells = (59..65).map { BlockPos(it, 3, 122) }.toSet()
        val blueTerminalCells = (59..65).map { BlockPos(it, 3, 65) }.toSet()

        // Until implicit placeability is calibrated, the placement-region set is the
        // explicit candidate spot centres only. It is NOT the published total placeable mask.
        val blueCenters = explicitSpots.filter { it.team == TeamId.BLUE }.map { it.center }.toSet()
        val redCenters = explicitSpots.filter { it.team == TeamId.RED }.map { it.center }.toSet()

        return MapImportCandidate(
            mapId = "farm_improved_2022_candidate",
            revision = "runtime-candidate-v2-full-fixture",
            authenticity = MapAuthenticity.COMMUNITY_IMPROVEMENT_BY_ORIGINAL_TRACK_AUTHOR,
            productionOriginal = false,
            coordinateSpace = CoordinateSpace(
                type = CoordinateSpaceType.SCHEMATIC_LOCAL,
                dimensions = Triple(125, 18, 191),
                sourceOffset = BlockPos(-61, 54, -95),
                absoluteProductionCoordinatesKnown = false
            ),
            sourceHash = EXPECTED_SHA256,
            routes = listOf(
                CandidateRoute("blue_branch_high_x", TeamId.BLUE, blueHigh),
                CandidateRoute("blue_branch_low_x", TeamId.BLUE, blueLow),
                CandidateRoute("red_branch_high_x", TeamId.RED, redHigh),
                CandidateRoute("red_branch_low_x", TeamId.RED, redLow)
            ),
            placementRegions = mapOf(
                TeamId.BLUE to PlacementRegion(TeamId.BLUE, blueCenters),
                TeamId.RED to PlacementRegion(TeamId.RED, redCenters)
            ),
            explicitTowerSpots = explicitSpots,
            teamGeometry = mapOf(
                TeamId.RED to CandidateTeamGeometry(
                    team = TeamId.RED,
                    mobSpawn = Vec3(26.0, 8.0, 71.0),
                    terminalCrossSection = RouteTerminalCrossSection(
                        TeamId.RED, BlockPos(62, 3, 122), CardinalHeading.NEG_Z, 7,
                        redTerminalCells, "MEASURED_FROM_SCHEMATIC"
                    ),
                    castleContactCandidate = CastleContactCandidate(
                        TeamId.RED, redTerminalCells, CardinalHeading.NEG_Z,
                        "INFERRED_SCHEMATIC_BOUNDARY_CANDIDATE", originalTriggerRule = null
                    )
                ),
                TeamId.BLUE to CandidateTeamGeometry(
                    team = TeamId.BLUE,
                    mobSpawn = Vec3(98.0, 8.0, 116.0),
                    terminalCrossSection = RouteTerminalCrossSection(
                        TeamId.BLUE, BlockPos(62, 3, 65), CardinalHeading.POS_Z, 7,
                        blueTerminalCells, "MEASURED_FROM_SCHEMATIC"
                    ),
                    castleContactCandidate = CastleContactCandidate(
                        TeamId.BLUE, blueTerminalCells, CardinalHeading.POS_Z,
                        "INFERRED_SCHEMATIC_BOUNDARY_CANDIDATE", originalTriggerRule = null
                    )
                )
            ),
            evidenceRefs = listOf(
                "CubeCraft_TD_Farm_runtime_candidate_v2.json",
                "CubeCraft_TD_Farm_integrity_fixture_v1.json"
            )
        )
    }

    fun run(): List<FixtureResult> {
        val runtime = MapRuntimeCompiler.compile(candidate())
        val report = MapRuntimeValidator.validate(runtime)
        val blue3 = runtime.explicitTowerSpots.count { it.team == TeamId.BLUE && it.footprint == FootprintSize.THREE_BY_THREE }
        val blue5 = runtime.explicitTowerSpots.count { it.team == TeamId.BLUE && it.footprint == FootprintSize.FIVE_BY_FIVE }
        val red3 = runtime.explicitTowerSpots.count { it.team == TeamId.RED && it.footprint == FootprintSize.THREE_BY_THREE }
        val red5 = runtime.explicitTowerSpots.count { it.team == TeamId.RED && it.footprint == FootprintSize.FIVE_BY_FIVE }

        val autoCentreProbe = ExplicitSpotPlacementResolver.resolve(
            runtime,
            PlacementRequest(TeamId.BLUE, BlockPos(29, 3, 11), FootprintSize.THREE_BY_THREE, autoCentre = true)
        )

        return listOf(
            FixtureResult("farm-full-map-valid", report.isValid, report.issues.map { "${it.code}:${it.fatal}" }),
            FixtureResult("farm-four-branches", runtime.routesById.size == 4),
            FixtureResult("farm-30-waypoints-each", runtime.routesById.values.all { it.nodes.size == 30 }),
            FixtureResult("farm-explicit-spot-counts", blue3 == 188 && red3 == 188 && blue5 == 8 && red5 == 8),
            FixtureResult("farm-authenticity-not-original", !runtime.productionOriginal && runtime.authenticity != MapAuthenticity.ORIGINAL),
            FixtureResult("farm-exact-castle-null", runtime.castleContactRegionsExact.values.all { it == null }),
            FixtureResult("farm-guard-anchors-null", runtime.guardAnchors.values.all { it.isEmpty() }),
            FixtureResult("farm-explicit-autocentre", autoCentreProbe is PlacementResolution.ExplicitSpot)
        )
    }
}
